<?php

function theme_factory_menu() {
  $items = array();
  $items['theme_factory/generate'] = array(
    'title' => t('Theme Factory'),
    'page callback' => '_theme_factory_get_form',
    'access arguments' => array('access content'),
    'description' => t('Theme Factory'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function _theme_factory_get_form() {
  return drupal_get_form('theme_factory_form');
}

function theme_factory_form($form, &$form_state) {
  $form['#attached']['css'] = array(
    drupal_get_path('module', 'theme_factory') . '/css/theme_factory.css',
  );
  $form['layout'] = array(
    '#type' => 'radios',
    '#title' => t('Type'),
    '#options' => array(
      "layout1" => t('<strong>Layout #1</strong>') . '<div id="layout1"><div class="box header"></div><div class="box masthead"></div><div class="box content"></div><div class="box sidebar"></div><div class="box footer"></div></div>' . t('<p class="layout-type")>Layout description #1.</p>'),
      "layout2" => t('<strong>Layout #2</strong>') . '<div id="layout2"><div class="box header"></div><div class="main-content"><div class="box masthead"></div><div class="box content"></div></div><div class="box sidebar"></div><div class="box footer"></div></div>' . t('<p class="layout-type")>Layout description #2.</p>'),
    ),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function theme_factory_form_submit($form_id, $form_values) {
  drupal_set_message(t('The form has been submitted.'));
}
